filebeat.inputs:
  - type: filestream
    paths:
      - /home/support/barbanet.log
    pipeline: "springboot_pipeline"
output.elasticsearch:
  hosts: ["http://192.168.1.225:9200"]
    #  index: "badpa-console-log"
    #  index: "badpa-console-log-%{+yyyy.MM.dd}"
  username: "elastic"
  password: "elastic"
